# Generated by Django 4.2.1 on 2023-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
