# Generated by Django 4.2.1 on 2023-07-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_mgm', '0002_customer_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
    ]
